### ISSUE TITLE
Hi, i have a little issue with the mod

### ISSUE THREAD

**Issue by zyiux** [PetitFrapo/NoMoreGrayFilter#1]
Hi, i love your mod, but i use "SuperExpert" mod and it uses the versus files, 
![20240323115410_1](https://github.com/PetitFrapo/NoMoreGrayFilter/assets/159499296/892e232f-a3a5-428e-b0ab-eda3d9234203)

**Comment by zyiux** [comment]
you should add options to change the gray filter, like disable versus button.

**Comment by PetitFrapo** [comment]
Hi, I will look into this once I get home. Sorry for not testing my mod enough ^^'

**Comment by zyiux** [comment]
> Hi, I will look into this once I get home. Sorry for not testing my mod enough ^^'
Dont worry, your mod is an original idea :D

**Comment by PetitFrapo** [comment]
It should be fixed, just need the update to be accepted on the index. If you want it now you can download the mod found in the releases and drop it in your mods folder. Thank you so much for using the mod and for reporting this bug!
