### ISSUE TITLE
Please fix or revert

### ISSUE THREAD

**Issue by Infernogd** [PetitFrapo/NoMoreGrayFilter#3]
The mod doesn't work properly anymore after the 1.03 update its grayed out again except versus mode please fix it or revert the update thanks!
![image_2024-03-24_034548693](https://github.com/PetitFrapo/NoMoreGrayFilter/assets/164727301/2d518d0f-3efc-4cf3-9c16-51f73c61b746)

**Comment by PetitFrapo** [comment]
Yes, I'm doing just that... I made a basic mistake...

**Comment by InfernoZv** [comment]
wow that was quick ok no worries

**Comment by PetitFrapo** [comment]
I have submitted it to the indexer, I just need to wait.

**Comment by InfernoZv** [comment]
Alr no worries thanks for fixing it
