### ISSUE TITLE
Creator Tab is different

### ISSUE THREAD

**Issue by Zeirous** [PetitFrapo/NoMoreGrayFilter#5]
Like the other issue described but this is with no other mods that have a button in the Creator tab this is how it looks even with this mod only so please fix this
![image](https://github.com/user-attachments/assets/daacbd3f-8494-445f-9ab4-f92049cc4c81)

**Comment by PetitFrapo** [comment]
Hey, sorry for not responding. 
I'm currently on vacation and don't have my computer to code any patch. I will try and see what causes the issue though.
I recommend that you disable the mod as I understand that this is annoying.

**Comment by SomeGDPerson123** [comment]
Yea I have the same issue... I think the best band-aid to make when you have the chance is probably make an option that forces the position of the options...

**Comment by OmgRod** [comment]
same for me too

**Comment by PetitFrapo** [comment]
I'll try and code a patch that has an option to force the position of the buttons. I'm really sorry that I can't do it right now but I'm still far from my PC.

**Comment by PetitFrapo** [comment]
Done!
